name: release_bin
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - name: Install Promu
        run: |
          GO111MODULE=off go get github.com/prometheus/promu
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run Promu Crossbuild
        run: |
          promu crossbuild

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ./.build
